---
- hosts: all
  tasks:
    - name: Install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
