---
- hosts: all
  tasks:
    - name: Disable SSH password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
      register: sshd_config
    
    - name: Restart SSHD daemon
      service:
        name: sshd
        state: restarted
      when: sshd_config.changed

    - name: Install base packages
      apt:
        update_cache: yes
        state: present
        name:
          - python3-pip
          - neofetch
          - sudo
          - curl
          - htop
          - tmux
          - vim
          - zsh
          - gcc
          - make
          - build-essential
    
    # Python dependency for ansible.builtin.expect
    - name: Install pexpect
      pip:
        name: pexpect
    
    - name: Install zsh
      apt:
        state: present
        name:
          - zsh
      register: zsh_installed

    - name: Install oh-my-zsh
      #shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      shell: echo contents > /root/hello.txt
      when: zsh_installed.changed
    
    - name: Check if Node.js is installed
      shell: command -v node
      register: node_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Install Node.js LTS repo
      shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      when: node_exists is failed
    
    - name: Install nodejs LTS
      apt:
        name: nodejs
        state: present
      when: node_exists is failed
    
    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
    
    # - name: Check if Rust is installed
    #   shell: command -v cargo
    #   register: cargo_exists
    #   changed_when: false
    #   ignore_errors: yes
    #   no_log: yes

    # - name: Install Rust
    #   shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    #   when: cargo_exists is failed
    