---
- hosts: all
  tasks:
    - name: Install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
          - vim
          - gcc
          - make
          - build-essential
    
    - name: Check if node is installed
      shell: command -v node
      register: node_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Install nodejs LTS repo
      when: node_exists is failed
      shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    
    - name: Install nodejs LTS
      apt:
        name: nodejs
        state: latest