---
- hosts: all
  tasks:
    - name: install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
    
    - name: check if node is installed
      shell: command -v node
      register: node_exists
      ignore_errors: yes

    - name: install node repository
      shell: "echo hello world"
