---
- hosts: all
  tasks:
    - name: Disable SSH password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
      register: sshd_config
    
    - name: Restart SSHD daemon
      service:
        name: sshd
        state: restarted
      when: sshd_config.changed

    - name: Install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - python3-pip
          - neofetch
          - sudo
          - curl
          - htop
          - tmux
          - vim
          - gcc
          - make
          - build-essential
    
    # Python dependency for ansible.builtin.expect
    - name: Install pexpect
      pip:
        name: pexpect
    
    - name: Check if Node.js is installed
      shell: command -v node
      register: node_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Install Node.js LTS repo
      shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      when: node_exists is failed
    
    - name: Install nodejs LTS
      apt:
        name: nodejs
        state: latest
      when: node_exists is failed
    
    - name: Install Rust
      expect:
        command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
        responses:
          'Proceed with installation (default)' : '1'
    
    # - name: Check if Rust is installed
    #   shell: command -v cargo
    #   register: cargo_exists
    #   changed_when: false
    #   ignore_errors: yes
    #   no_log: yes

    # - name: Install Rust
    #   shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    #   when: cargo_exists is failed
    