---
- hosts: all
  tasks:
    - name: install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
          - vim
          - gcc
          - make
          - build-essential
    
    - name: check if node is installed
      shell: command -v node
      register: node_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Creating a .txt file in $HOME
      shell: echo "Save me!" > $HOME/test.txt