---
- hosts: all
  tasks:
    - name: Install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
          - vim
          - gcc
          - make
          - build-essential
    
    - name: Check if node is installed
      shell: command -v node
      register: node_exists
      changed_when: false
      ignore_errors: yes
      no_log: yes

    - name: Install nodejs LTS repo
      shell: curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
      when: node_exists is failed
    
    - name: Install nodejs LTS
      apt:
        name: nodejs
        state: latest
    
    - name: Disable SSH password auth
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^#PasswordAuthentication yes"
        line: "PasswordAuthentication no"
      register: sshd_config
    
    - name: Restart SSHD daemon
      service:
        name: sshd
        state: restarted
      when: sshd_config.changed