---
- hosts: all
  tasks:
    - name: install base packages
      apt:
        update_cache: yes
        state: latest
        name:
          - neofetch
          - curl
          - htop
          - tmux
          - gcc
          - make
          - build-essential
    
    - name: check if node is installed
      shell: command -v python3
      register: node_exists
      changed_when: false
      ignore_errors: yes

    - name: install node repository
      shell: "echo hello world"
